#!/bin/python3

import os

"""
    For both kangaroo k1 & k2 to meet each other after a certain jump, j implies that
        x1+(j*v1) = x2+(j*v2); where j represents numbers of jump

    Since the constraint for x1 and x2 is x1<x2,
    Therefore, we will move x1 to x2 to form x2-x1
        => x2-x1 = (j*v1) - (j*v2)
           x2-x1 = j*(v1-v2)
           (x2-x1)/(v1-v2)=j
           
        As j is an integer, it also implies that (x2-x1)%(v1-v2)=0
        As x1<x2 and for k1 to be able to catch up with k2, v1 must be greater than v2.
        So, it only prints YES when meet these conditions.
"""
def kangaroo(x1, v1, x2, v2):
    return "YES" if v1-v2>0 and (x2-x1)%(v1-v2)==0 else "NO"

"""
    INPUT: x1 v1 x2 v2
    OUTPUT: YES/NO
"""
# Generated by hackerrank
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])
    v1 = int(x1V1X2V2[1])
    x2 = int(x1V1X2V2[2])
    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')
    fptr.close()
